name: Run Unit Test and Upload Coverage Report
on:
  # Triggered whenever push to main 
  push:
    branches: [ "main", "iteration_1" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "main" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:
    
jobs:
  build-run-upload:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash       # specify bash for use with docker container
    container:
      image: osrf/ros:humble-desktop # use ROS Humble from docker hub repository
    steps:
      # We want to use GitHub CI checkout version 3 to check out our branch
      - uses: actions/checkout@v3
      
      # Install some system pacakges
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y doxygen lcov gcovr pandoc
          source /opt/ros/humble/setup.bash
          sudo apt install -y \
            ros-${ROS_DISTRO}-catch-ros2 \
            ros-${ROS_DISTRO}-webots-ros2-driver \
            ros-${ROS_DISTRO}-nav2-msgs
          
      # Run all unit test, integration test, and generate combined coverage report
      - name: Build, run unit test, and generate coverage report
        run: |
          ./do-tests-and-coverage.bash
          ./do-docs.bash
          cat build/test_coverage_merged.info

      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required (must add token in your github repo)
          files: ${{github.workspace}}/build/test_coverage_merged.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)      
          disable_search: true # optional (default = false)
          plugin: none         # optional (xcode, gcov, pycoverage)
